# Site settings
title: Daniel Caine - Designer and front-end developer
email: audaci7y@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Daniel Caine, web designer based in Bristol, England. Bs1
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caine.design" # the base hostname & protocol for your site
twitter_username: A7DC
github_username:  A7DC

# Build settings
markdown: kramdown